import { useMemo } from "react";
import { useLocale } from "@agenticx/ui";

const copy = {
  zh: {
    checkingAuth: "校验登录状态…",
    signIn: "登录",
    signUp: "注册",
    authTitle: "登录 Machi",
    authSubtitle: "使用 AgenticX 账号进入企业工作台。",
    email: "邮箱",
    username: "用户名",
    password: "密码",
    confirmPassword: "确认密码",
    loginAction: "登录并进入工作台",
    signupAction: "创建账号",
    wechatComingSoon: "微信登录即将上线，请先使用邮箱登录",
    passwordMismatch: "两次密码不一致",
    signInSuccess: "登录成功",
    signUpSuccess: "注册成功，请登录",
    signOut: "退出登录",
    settings: "设置",
    history: "历史会话",
    noHistory: "暂无历史，点击 New chat 开始",
    newChat: "New chat",
    deepResearch: "Deep research",
    backToChat: "← 返回对话",
    modelService: "模型服务",
    defaults: "默认模型",
    webSearch: "网络搜索",
    parser: "文档解析",
    chat: "聊天设置",
    general: "常规设置",
    routeLabel: "路由",
    complianceTitle: "合规拦截",
    chatErrorTitle: "聊天请求失败",
  },
  en: {
    checkingAuth: "Checking authentication…",
    signIn: "Sign In",
    signUp: "Sign Up",
    authTitle: "Log in to Machi",
    authSubtitle: "Use your AgenticX account to enter enterprise workspace.",
    email: "Email",
    username: "Username",
    password: "Password",
    confirmPassword: "Confirm Password",
    loginAction: "Login and enter workspace",
    signupAction: "Create account",
    wechatComingSoon: "WeChat login coming soon. Please use email login.",
    passwordMismatch: "Passwords do not match",
    signInSuccess: "Logged in",
    signUpSuccess: "Registered, now sign in",
    signOut: "Sign out",
    settings: "Settings",
    history: "History",
    noHistory: "No history yet. Start with New chat.",
    newChat: "New chat",
    deepResearch: "Deep research",
    backToChat: "← Back to chat",
    modelService: "Model service",
    defaults: "Default models",
    webSearch: "Web search",
    parser: "Document parser",
    chat: "Chat settings",
    general: "General settings",
    routeLabel: "Route",
    complianceTitle: "Compliance block",
    chatErrorTitle: "Chat request failed",
  },
} as const;

export function usePortalCopy() {
  const { locale } = useLocale();
  return useMemo(() => (locale === "en" ? copy.en : copy.zh), [locale]);
}

